services:
  astro:
    build:
      context: astro
      dockerfile: ../Dockerfile.astro
    develop: # this watch block helps when developing
      watch:
        - action: sync
          path: ./astro/src
          target: /app/src
          ignore:
            - ./node_modules/
        - action: rebuild
          path: ./astro/package.json
        - action: rebuild
          path: ./astro/astro.config.json
    entrypoint: npm run dev # run this command when developing
    environment: # see astro/src/env.d.ts
      SITE: http://localhost
      WP_SITE: http://wordpress
      GRAPHQL_URL: http://wordpress/graphql
      ASTRO_TELEMETRY_DISABLED: 1 # https://astro.build/telemetry/
    restart: always
    ports:
      - "3000:4321"
    depends_on:
      - wordpress
    networks:
      astro_net_1:
        ipv4_address: 172.16.56.21

  wordpress:
    build:
      context: wordpress
      dockerfile: ../Dockerfile.wordpress
    restart: always
    ports:
      - "8080:80" # disable after initial startup
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DATABASE}
      WORDPRESS_INTERNAL_URL: http://wordpress
      WORDPRESS_AUTH_KEY: ${WORDPRESS_AUTH_KEY}
      WORDPRESS_SECURE_AUTH_KEY: ${WORDPRESS_SECURE_AUTH_KEY}
      WORDPRESS_LOGGED_IN_KEY: ${WORDPRESS_LOGGED_IN_KEY}
      WORDPRESS_NONCE_KEY: ${WORDPRESS_NONCE_KEY}
      WORDPRESS_AUTH_SALT: ${WORDPRESS_AUTH_SALT}
      WORDPRESS_SECURE_AUTH_SALT: ${WORDPRESS_SECURE_AUTH_SALT}
      WORDPRESS_LOGGED_IN_SALT: ${WORDPRESS_LOGGED_IN_SALT}
      WORDPRESS_NONCE_SALT: ${WORDPRESS_NONCE_SALT}
      WORDPRESS_DEBUG: true
      WORDPRESS_CONFIG_EXTRA: "define( 'WP_DEBUG_LOG', true ); define( 'WP_DEBUG_DISPLAY', true );"
    volumes:
      - ./wordpress/wp-content:/var/www/html/wp-content
    networks:
      astro_net_1:
        ipv4_address: 172.16.56.22

  db:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    restart: always
    volumes:
      - type: volume
        source: db
        target: /var/lib/mysql
        volume:
          nocopy: false

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${WORDPRESS_DATABASE}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}

    networks:
      astro_net_1:
        ipv4_address: 172.16.56.23

networks:
  astro_net_1:
    ipam:
      driver: default
      config:
        - subnet: "172.16.56.0/24"

volumes:
  db:
    name: astro-wp-db

