FROM wordpress:php8.1

EXPOSE 80

# Set workdir
WORKDIR /var/www/html

# Copy php uploads config file, added to /var/www/html on container startup
COPY ./uploads.ini /usr/local/etc/php/conf.d/uploads.ini

# Copy wordpress content, added to /var/www/html on container startup
COPY ./default-wp-content/plugins/wp-graphql /usr/src/wordpress/wp-content/plugins/wp-graphql
